### ISSUE TITLE
Support other stacks than cflinuxfs2

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry-incubator/compile-extensions#11]
We're facing a problem because all buildpacks which use this library (which are a lot - node, python, ruby, go, dotnetcore) only support one single stack - `cflinuxfs2`.

We'd like to offer our CF users multiple stacks in parallel, i.e. `cflinuxfs2` and `cflinuxfs2-customized`. These two stacks are very similar and all of the above mentioned buildpacks would just work fine. But when pushing apps using `cflinuxfs2-customized` with one of the default buildpacks, it fails because `check_stack_support ` expects `cflinuxfs2`.

We agree that it makes sense for a buildpack to expose with which stack it runs (i.e. to differentiate between linux or windows), but we think it's rather unfortunate to expect a specific stack name. 

Would it make sense to introduce something like `stack type`? Stacks would then expose this type i.e. `linux` and `windows` and `check_stack_support` could check for it.

**Comment by sclevine** [comment]
One problem with allowing the core buildpacks to run with any stack is that the binaries (and other object code) provided by each buildpack are dynamically linked to the libraries provided by cflinuxfs2. Even if we introduced a concept of "stack type," we would not be able to guarantee that the buildpack binaries would run on all stacks of that type.

More generally, making any changes to the rootfs could result in a buildpack not running for difficult to determine reasons, due to the rootfs providing something different from what the buildpack expects.

What we could do is introduce an environment variable that disables stack checking. You could set this in your staging environment variables groups to allow all of your core buildpacks to run on any stack. I'm not convinced that we should do this though, because it's difficult to know whether a change to the rootfs could break one of the buildpacks.

**Comment by MatthiasWinzeler** [comment]
Thanks for the response. I understand that it does not make sense to assume that these buildpacks run on all stacks of the same type since they're explicitly built for this one stack.

However, in our case, the changes are so small that we're feeling confident it won't break anything.

Btw, do you know about any other way to set `CF_STACK` for our custom `cflinuxfs2_custom` stack so that it passes stack checking?

We couldn't find a way by looking at the code - `CF_STACK`, the stack name that is checked seems to come straight from CC's `app.stack.name` which is most likely the value the user enters on the cli (which must be `cflinuxfs2_custom` in our case).

We would really appreciate a way to disable stack checking!

**Comment by sclevine** [comment]
Your best bet would be to fork the buildpacks and add your custom stack to the `cf_stacks` keys in each buildpack's `manifest.yml` file.

For example: https://github.com/cloudfoundry/php-buildpack/blob/master/manifest.yml#L74

Alternatively, if you don't need the original stack to be present, you could replace `cflinuxfs2` with `cflinuxfs2_custom` and just call it `cflinuxfs2`.

**Comment by MatthiasWinzeler** [comment]
That's what we feared - but we'd like to avoid forking buildpacks, since this prevents users from bringing their own buildpacks (without modification).

Would you welcome a PR adding `CF_DISABLE_STACK_CHECK`?

**Comment by sclevine** [comment]
We think that adding this env var (which can't start with `CF_`, because that prefix is reserved) would cause problems when we introduce cflinuxfs3 (a xenial-based rootfs). We also think that upcoming CC features (stack-to-buildpack association that is determined by the platform) would break you again later anyways.

( @dgodd let me know if I missed anything )

**Comment by MatthiasWinzeler** [comment]
OK, that's understandable.

Anyway, we found another way to implement this feature (by providing an isolation segment of cells with the other stack under the same name) so from my POV, feel free to close it.

**Comment by sclevine** [comment]
Sounds good.
