### ISSUE TITLE
Allow online buildpacks access to more versions than cached

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-incubator/compile-extensions#7]
First of all not sure if this is the correct repository.  I'd be happy to resubmit the issue to whatever repo is appropriate. 

The buildpack team has a very specific and well documented set of rules for what versions of various platforms are to be included in cached versions of buildpacks, which is great!  I'm under the assumption that these rules are especially important in relation to keeping cached buildpack sizes to a minimum which is also very important.

That said, I have some customers that are very concervative.  They value stability and predictability over security, new features, bug fixes, etc.  For the sake of discussion they largely use the node buildpack.  For some of their applications they'd prefer to specify a fixed node version in their package.json and upgrade to newer versions at their convenience and release cycle.  This is a problem when only a limited number of older versions are available for use in the buildpack as the CF platform upgrade cycle essentially imposes release requirements upon their projects that may conflict with their own release cycles and processes.

What are the thoughts on the idea of continuing to limit the platform dependencies for cached versions of the buildpack, but, allow for non cached users of the buildpack to continue to use older versions of platform dependencies beyond the version that the current standards dictate?

Perhaps extend manifest.yml to include all versions pivotal has ever built but add a flag to indicate which versions should be cached as part of a build operation?

Granted I know it is trivial to fork the buildpack and simply add whatever we want to the manifest (which is what we do today) but we'd like to remain stock where possible.

Thoughts?

**Comment by flavorjones** [comment]
Hi, @youngm -

Thanks for asking this question!

It's possible to specify 'wildcards' in an application's `package.json`, so that it matches a range of versions. This might actually be the best solution, striking a balance between stability/security and ease of application development and upgrade. You can read more about this here: https://docs.npmjs.com/misc/semver

An alternative is that we've open-sourced all the tooling you need to create a custom buildpack with custom artifacts in the buildpack.

If you want to use our OSS binaries, you can go through the git history for the `manifest.yml` file for any buildpack and see a complete history of all the artifacts we've shipped in a buildpack; and add the ones you like to your custom buildpack.

If you want to create your own custom binaries, you can use `binary-builder` to compile them, and again put them into a custom buildpack.

We decided not to allow outbound network connections to download other artifacts in order to maintain a guarantee that your app will stage in "disconnected" or "offline" environments (meaning, without access to the public internet). This is a philosophical difference with the Java buildpack, which notably ships an uncached buildpack by default in `cf-release`.

We'd be happy to work with you to automate crafting the right buildpack for your customers. You can ping either @Dannyzen or me and we're happy to chat about it!

I hope I've answered your question? I'm going to close this issue, but if you have questions, please respond here and we can reopen it.

**Comment by youngm** [comment]
@flavorjones I'm well aware we can fork and build our own buildpacks, etc.  The reason for submitting an issue was to suggest new capabilities into the main line.

So, let me ask a slightly different question.  You mentioned in your response.  

> We decided not to allow outbound network connections to download other artifacts in order to maintain a guarantee that your app will stage in "disconnected" or "offline" environments.

So are you saying that you have no interest in enhancing the buildpack to improve experiences for those who wish to use the bulidpack online because offline mode is the only functional mode of significance to the project?

If yes then that is good to know and this issue is irrelevant.

If no, and you do care about both online and offline functionality why not consider this feature request?

**Comment by flavorjones** [comment]
@youngm My first response is to suggest using "wildcards" in an application's package.json. This applies to the PHP and Go buildpacks, and soon will apply to the Ruby buildpack as well (waiting on an upstream release of Bundler). I believe this addresses the underlying need you're describing. If it doesn't, can you help me understand why it doesn't?

The removal of older versions of interpreters/compilers was actually done with the intent of reducing security vulnerability cross-section, and has nothing to do with disallowing external connections. I brought up disallowing external connections to provide additional context around why we don't allow downloading of additional dependencies in the cached buildpack.

I understand the specific implementation you're driving towards, but I'm asking for help understanding the specific use case you're trying to address, so I can properly form an opinion about the tradeoffs.

**Comment by youngm** [comment]
@flavorjones You're right.  Sorry I forgot to address the wildcard idea.  Our customer was actually using wildcards and a recent auto upgrade of the buildpack from Node 0.10.40 to 0.10.42 broke them and caused an outage.  This has caused them to be a bit jumpy about the buildpack updating their project outside of their normal release process.

I agree that wildcards is the right solution for most project that wish to just deploy their app and forget it.  We're just looking for a way to best support these more particular customers and thought this might be a useful way to address this for some of our customers and perhaps some of yours as well.

In the case of Node, if a customer wishes to specify a specific node version in the package.json why not let the buildpack honor it? (If it can)  If the customer wants auto security patches using a wildcard then lets support that too.

Does that help?
